name: CI

# Ejecuta el workflow en cada push o pull request a cualquier rama
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Run Tests & Coverage
    runs-on: ubuntu-latest

    steps:
      # Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instala dependencias
      - name: Install dependencies
        run: npm ci
        working-directory: frontend/tcs-challenge

      # Corre tests con coverage
      - name: Run tests
        run: npm test -- --watch=false --browsers=ChromeHeadless
        working-directory: frontend/tcs-challenge

      # Publica resultados de coverage (opcional, si usas cobertura en archivos)
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: frontend/tcs-challenge/coverage
